# Generated by Django 2.2.7 on 2019-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalhistry',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirm', 'confirm'), ('cancel', 'Cancel')], max_length=50, null=True),
        ),
    ]
