# Generated by Django 2.2.7 on 2019-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_withdrawalhistry_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalhistry',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
